# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df41a79c95b4ca4e57ed5a65de395a25a730a35bae5654ff5e5f61a802718de9ca1d23e5ff21c982a284487508cdc7eeca509f6acce3ec316863fd448a567a32

test:
  secret_key_base: 1733cf8d22a4e4db27f6d9cc5b4cad1f11024fd71f80e4f59f6e4e06acf36209e57837e6c75441b9fa885544df178351fa54ccf51f9ba98734b069dd86609dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
